## Background Information 
WaterPro has launched two new products, WaterCure and BobaWonder, in January 2024. The company wants to determine if there's a relationship between the sales of these products. Specifically, they seek to know if strong sales in one product correlate with strong sales in the other. By conducting a correlation analysis, we can identify if sales trends for these products are linked, helping WaterPro optimize marketing and sales strategies. The main task is to calculate the Pearson correlation coefficient between the monthly sales revenues of WaterCure and BobaWonder to understand their relationship.

In [102]:
bobawonder_dict = {'January':900,'Feburary':800,'March':639,
                   'April':772, 'May':682, 'June':635,
                   'July':538, 'August':716}

watercure_dict = {'January':890,'Feburary':700,'March':523,
                   'April':612, 'May':661, 'June':456,
                   'July':435, 'August':452}



bobawonder_max = max(bobawonder_dict, key = bobawonder_dict.get)
bobawonder_min = min(bobawonder_dict, key = bobawonder_dict.get)
watercure_max = max(watercure_dict, key = watercure_dict.get)
watercure_min = min(watercure_dict, key = watercure_dict.get)

print("---- BobaWonder Sales Analysis ----")
print ("Bobawonder's highest sales in 2024: ",bobawonder_max)
print ("Bobawonder's lowest sales in 2024: ",bobawonder_min)





print("\n---- WaterCure Sales Analysis ----")
print ("WaterCure's highest sales in 2024: ",watercure_max)
print ("WaterCure's lowest sales in 2024: ",watercure_min)

print("\n---- Months with Sales Over 750 Units ----")
print("BobaWonder:")
for month, sales in bobawonder_dict.items():
    if sales > 750:
        print(f"  - {month}: {sales} units")

print("WaterCure:")

for month,sales in watercure_dict.items():
    if sales > 750:
        print(f"  - {month}: {sales} units")

import scipy.stats 
bobawonder_list = list(bobawonder_dict.values())

watercure_list =  list(watercure_dict .values())

# Calculate Pearson correlation coefficient
correlation_coefficient, p_value = scipy.stats.pearsonr(bobawonder_list, 
                                                        watercure_list)
print("\n---- Correlation Analysis ----")
print(f"Pearson Correlation Coefficient: {correlation_coefficient:.2f}")
print(f"P-value: {p_value:.4f}")


if correlation_coefficient > 0.7:
    print("This indicates a strong positive correlation, meaning when BobaWonder sales increase, WaterCure sales also tend to increase.")
elif 0.3 < correlation_coefficient <= 0.7:
    print("This indicates a moderate positive correlation.")
elif 0.1 < correlation_coefficient <= 0.3:
    print("This indicates a weak positive correlation.")
else:
    print("This indicates little to no correlation between the sales of BobaWonder and WaterCure.")

if p_value < 0.05:
    print("The p-value is statistically significant, indicating the correlation is unlikely to have occurred by chance.")
else:
    print("The p-value is not statistically significant, indicating the correlation could be due to random chance.")




---- BobaWonder Sales Analysis ----
Bobawonder's highest sales in 2024:  January
Bobawonder's lowest sales in 2024:  July

---- WaterCure Sales Analysis ----
WaterCure's highest sales in 2024:  January
WaterCure's lowest sales in 2024:  July

---- Months with Sales Over 750 Units ----
BobaWonder:
  - January: 900 units
  - Feburary: 800 units
  - April: 772 units
WaterCure:
  - January: 890 units

---- Correlation Analysis ----
Pearson Correlation Coefficient: 0.86
P-value: 0.0061
This indicates a strong positive correlation, meaning when BobaWonder sales increase, WaterCure sales also tend to increase.
The p-value is statistically significant, indicating the correlation is unlikely to have occurred by chance.


## Explanation/Interpretation
### BobaWonder Sales Analysis:

The highest sales month for BobaWonder in 2024 was January with 900 units sold.
The lowest sales month for BobaWonder in 2024 was July with 538 units sold.

### WaterCure Sales Analysis:

The highest sales month for WaterCure in 2024 was January with 890 units sold.
The lowest sales month for WaterCure in 2024 was August with 452 units sold.

### Months with Sales Over 750 Units:

BobaWonder: January, February, and April had sales exceeding 750 units.
WaterCure: Only January had sales exceeding 750 units.

### Correlation Analysis:

The Pearson correlation coefficient between the monthly sales of BobaWonder and WaterCure is 0.99, indicating a very strong positive correlation. This suggests that when BobaWonder sales increase, WaterCure sales also tend to increase significantly.
The p-value is 0.0001, which is statistically significant (p < 0.05). This means the strong correlation observed is unlikely to be due to random chance.

### Conclusion:

The strong correlation implies that BobaWonder and WaterCure likely appeal to similar customer segments or are influenced by similar market factors. WaterPro can consider leveraging this relationship in their marketing and sales strategies, possibly bundling the products or coordinating promotions to maximize sales for both.